# Generated by Django 5.1.7 on 2025-03-30 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
