services:
  nginx:
    build:
      args:
        env: dev
    volumes:
      - ./staticfiles:/usr/share/nginx/static   

  static_files:
    environment:
      - env=dev
    ports:
      - "8000:8000"
    volumes:    
      - ./static_files:/app/

  tournament:
    environment:
      - env=dev
    ports:
      - "8001:8001"
    volumes:
      - ./tournament:/app/

  match:
    environment:
      - env=dev
    ports:
      - "8002:8002"
    volumes:
      - ./match:/app/
