version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    networks:
      - transcendence_network
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.5
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - transcendence_network


  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    networks:
      - transcendence_network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
      
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.5
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - transcendence_network

networks:
  transcendence_network:
    external: true
