services:
  nginx:
    build:
      args:
        env: dev
    volumes:
      - ./staticfiles:/usr/share/nginx/static   

  static_files:
    environment:
      - env=dev
    ports:
      - "${static_files_port}:${static_files_port}"
    volumes:    
      - ./static_files:/app/

  tournament:
    build:
      context: ./tournament
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
    ports:
      - "${tournament_port}:${tournament_port}"
    volumes:
      - ./tournament:/app/

  user:
    build:
      context: ./user
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
    env_file:
      - .env
    ports:
      - "${user_port}:${user_port}"
    volumes:
      - ./user:/app/

  match:
    build:
      context: ./match
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
    ports:
      - "${match_port}:${match_port}"
    volumes:
      - ./match:/app/

  authentication:
    build:
      context: ./authentication
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
    ports:
      - "${authentication_port}:${authentication_port}"
    volumes:
      - ./authentication:/app/

  databaseapi:
    build:
      context: ./databaseapi
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
    ports:
      - "${databaseapi_port}:${databaseapi_port}"
    volumes:
      - ./databaseapi:/app/

  api_gateway:
    environment:
      - env=dev
    ports:
      - "${api_gateway_port}:${api_gateway_port}"
    volumes:
      - ./api_gateway:/app/
