services:
  nginx:
    depends_on:
      - tournament
      - static_files
    container_name: ctn_nginx
    build :
      # Docker file location
      context: ./nginx/
      args:
        env: prod
    image: img_nginx
    ports: # Ports => Link the port from container to host
      - "443:443" #https
      - "80:80" #http
    volumes:
      - staticvol:/usr/share/nginx/static  # Bind mount des fichiers statiques
    networks:
      - transcendence_network
    restart: on-failure

  tournament:
    # depends_on:
    #   - blah
    container_name: ctn_tournament
    build :
      # Docker file location
      args:
        env: prod
      context: ./tournament/
    image: img_tournament
    # Expose => Expose a port within a Docker Networks. The port is then not available for the host.
    # expose:
    #   - "8001"
    volumes:
      - staticvol:/app/staticfiles
    networks:
      - transcendence_network
    restart: always # need to double check the 

  static_files:
    # depends_on:
    #   - blah
    container_name: ctn_static_files
    build :
      args:
        env: prod  
      # Docker file location
      context: ./static_files/
    image: img_static_files
    # Expose => Expose a port within a Docker Networks. The port is then not available for the host.
    expose:
      - "8000"
    ports: # Ports => Link the port from container to host
      - "8000:8000" #https
    environment:
      - DJANGO_ENV=development
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    restart: always # need to double check the 

volumes:
  staticvol:
    driver: local

networks:
  transcendence_network:
    name: transcendence_network
    driver : bridge # for making bind-mount

