services:
  nginx:
    depends_on:
      - tournament
      - static_files
    container_name: ctn_nginx
    build :
      context: ./nginx/
      args:
        env: prod
    image: img_nginx
    ports:
      # - "443:443" #https NOT WORKING AT 42!!!
      # - "80:80" #http NOT WORKING AT 42!!!
      - "8443:443"
      - "8000:80"
    volumes:
      - staticvol:/usr/share/nginx/static
    networks:
      - transcendence_network
    restart: on-failure

  tournament:
    container_name: ctn_tournament
    build :
      context: ./tournament/
    environment:
      - env=prod
      - port=8001
      - name=tournament
      - PI_DOMAIN=1140-46-193-66-225.ngrok-free.app
    ports:
      - "8002:8000"
    image: img_tournament
    volumes:
      - staticvol:/app/staticfiles
    networks:
      - transcendence_network
    restart: always

  match:
    container_name: ctn_match
    build :
      context: ./match/
    environment:
      - env=prod
      - port=8002
      - name=match
      - PI_DOMAIN=1140-46-193-66-225.ngrok-free.app
    image: img_match
    volumes:
      - staticvol:/app/staticfiles
    networks:
      - transcendence_network
    restart: always 

  static_files:
    container_name: ctn_static_files
    build :
      context: ./static_files/
    environment:
      - env=prod
      - port=8000
      - name=static_files
      - PI_DOMAIN=1140-46-193-66-225.ngrok-free.app
    image: img_static_files
    ports:
      - "8080:8000"
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    restart: always

volumes:
  staticvol:
    driver: local

networks:
  transcendence_network:
    name: transcendence_network
    driver : bridge

