services:
  nginx:
    build:
      args:
        env: dev
    volumes:
      - ./staticfiles:/usr/share/nginx/static        
  static_files:
    build:
      args:
        env: dev
    volumes:
      # - ./staticfiles:/app/staticfiles
      - ./static_files:/app
  tournament:
    volumes:
      - ./tournament:/app/
