services:
  nginx:
    depends_on:
      user:
        condition: service_healthy
      # tournament:
      #   condition: service_healthy
      # static_files:
      #   condition: service_healthy
    container_name: ctn_nginx
    build :
      context: ./nginx/
      args:
        env: prod
    environment:
      - static_files_port=${static_files_port}
      - tournament_port=${tournament_port}
      - match_port=${match_port}
    image: img_nginx
    ports:
      # - "443:443" #https NOT WORKING AT 42!!!
      # - "80:80" #http NOT WORKING AT 42!!!
      - "8443:443"
      - "8000:80"
    volumes:
      - staticvol:/usr/share/nginx/static
    networks:
      - transcendence_network
    restart: on-failure

  tournament:
    container_name: ctn_tournament
    build :
      context: ./tournament/
    environment:
      - env=prod
      - port=${tournament_port}
      - name=tournament
      - pi_domain=${PI_DOMAIN}
    image: img_tournament
    volumes:
      - staticvol:/app/staticfiles
    networks:
      - transcendence_network
    restart: always

  match:
    container_name: ctn_match
    build :
      context: ./match/
    environment:
      - env=prod
      - port=${match_port}
      - name=match
      - pi_domain=${PI_DOMAIN}
      - rasp=${rasp}
    image: img_match
    volumes:
      - staticvol:/app/staticfiles
    networks:
      - transcendence_network
    restart: always 

  static_files:
    container_name: ctn_static_files
    build :
      context: ./static_files/
    environment:
      - env=prod
      - port=${static_files_port}
      - name=static_files
      - pi_domain=${PI_DOMAIN}
    image: img_static_files
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    restart: always

  # USERS
  user:
    extends:
      file: ./user/_docker/user_compose.yaml
      service: user

  user_db:
    extends:
      file: ./user/_docker/user_compose.yaml
      service: user_db

  # user:
  #   depends_on:
  #     - postgres
  #   container_name: ctn_user
  #   build :
  #     context: ./user/
  #   environment:
  #     - env=prod
  #     - name=user
  #     - port=${user_port}
  #     - pi_domain=${PI_DOMAIN} # maybe not set up yet
  #   env_file: # ! Maybe delete depending on which postgres data I need
  #     - .env
  #   image: img_user
  #   networks:
  #     - transcendence_network
  #   volumes:
  #     - staticvol:/app/staticfiles
  #   healthcheck:
  #     # Health check done in non root user
  #     test: ["CMD", "curl", "-f", "http://localhost:${user_port}/health/"]
  #     interval: 1m30s    # How often to run the health check (every 90 seconds)
  #     timeout: 5s       # Maximum time to wait for the check to complete
  #     retries: 5         # Number of consecutive failures needed to mark container as unhealthy
  #     start_period: 30s  # Initial grace period where failures don't count (container startup time)
  #   restart: always

  # admin:
  #   container_name: ctn_admin
  #   build :
  #     context: ./admin/
  #   environment:
  #     - env=prod
  #     - name=admin
  #     - port=${admin_port}
  #     - pi_domain=${PI_DOMAIN} # maybe not set up yet
  #   env_file: # ! Maybe delete depending on which postgres data I need
  #     - .env
  #   image: img_admin
  #   networks:
  #     - transcendence_network
  #   volumes:
  #     - staticvol:/app/staticfiles
  #   restart: always

  # postgres:
  #   image: postgres:latest
  #   container_name: ctn_postgres
  #   environment:
  #     - name=postgres
  #     - pi_domain=${PI_DOMAIN}
  #     - port=${postgres_port}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   env_file:
  #     - .env
  #   # HOST_PORT:CONTAINER_PORT
  #   ports:
  #     - "5433:5432"
  #   healthcheck:
  #     # Health check done in non root user
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s
  #   volumes:
  #     # Bind mount for db in local
  #     - postgres_volume:/var/lib/postgresql/data
  #     # Init script for init db and users
  #     - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  #   networks:
  #     - transcendence_network
  #   restart: always


volumes:
  
  # Seb Static files volumes
  staticvol:
    driver: local
  
  user_db_volume:
    # Use the local driver for the volume
    driver: local
    name: user_db_volume
    driver_opts:
      # Specify the type as 'none' to use a bind mount
      type: none
      # When assigned to a container, the posgreSQL will reflect what's in this specified path.
      device: '/home/volumes_transcendence/postgres/user'
      # Bind the specified host path to the volume
      o: bind


networks:
  transcendence_network:
    name: transcendence_network
    driver : bridge