services:
  nginx:
    depends_on:
      - tournament
      - static_files
    container_name: ctn_nginx
    build :
      context: ./nginx/
      args:
        env: prod
    environment:
      - static_files_port=${static_files_port}
      - tournament_port=${tournament_port}
      - match_port=${match_port}
    image: img_nginx
    ports:
      # - "443:443" #https NOT WORKING AT 42!!!
      # - "80:80" #http NOT WORKING AT 42!!!
      - "8443:443"
      - "8000:80"
    volumes:
      - staticvol:/usr/share/nginx/static
    networks:
      - transcendence_network
    restart: on-failure

  tournament:
    container_name: ctn_tournament
    build :
      context: ./tournament/
    environment:
      - env=prod
      - port=${tournament_port}
      - name=tournament
      - pi_domain=${PI_DOMAIN}
    # ports:
    #   - "8002:8000"
    image: img_tournament
    volumes:
      - staticvol:/app/staticfiles
    networks:
      - transcendence_network
    restart: always

  match:
    container_name: ctn_match
    build :
      context: ./match/
    environment:
      - env=prod
      - port=${match_port}
      - name=match
      - pi_domain=${PI_DOMAIN}
      - rasp=${rasp}
    image: img_match
    volumes:
      - staticvol:/app/staticfiles
    networks:
      - transcendence_network
    restart: always 

  static_files:
    container_name: ctn_static_files
    build :
      context: ./static_files/
    environment:
      - env=prod
      - port=${static_files_port}
      - name=static_files
      - pi_domain=${PI_DOMAIN}
    image: img_static_files
    # ports:
    #   - "8080:8000"
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    restart: always

volumes:
  staticvol:
    driver: local

networks:
  transcendence_network:
    name: transcendence_network
    driver : bridge
