services:
  nginx:
    build:
      args:
        env: dev
    volumes:
      - ./staticfiles:/usr/share/nginx/static        
  static_files:
    build:
      args:
        env: dev
    volumes:
      - ./static_files:/app/
  tournament:
    build:
      args:
        env: dev
    volumes:
      - ./tournament:/app/
