services:
  nginx:
    volumes:
      - ./staticfiles:/usr/share/nginx/static     
  static_files:
    volumes:
      - ./staticfiles:/app/staticfiles
  tournament:
    volumes:
      - ./tournament:/app/
