services:
  nginx:
    depends_on:
      - tournament
      - static_files
    container_name: ctn_nginx
    build :
      # Docker file location
      context: ./nginx/
    image: img_nginx
    ports: # Ports => Link the port from container to host
      - "443:443" #https
      - "80:80" #http
    networks:
      - transcendence_network
    restart: on-failure

  tournament:
    # depends_on:
    #   - blah
    container_name: ctn_tournament
    build :
      # Docker file location
      context: ./tournament/
    image: img_tournament
    # Expose => Expose a port within a Docker Networks. The port is then not available for the host.
    expose:
      - "8000"
    networks:
      - transcendence_network
    restart: on-failure # need to double check the 

  static_files:
    # depends_on:
    #   - blah
    container_name: ctn_static_files
    build :
      # Docker file location
      context: ./static_files/
    image: img_static_files
    # Expose => Expose a port within a Docker Networks. The port is then not available for the host.
    expose:
      - "8001"
    # ports: # Ports => Link the port from container to host
    #   - "8001:8001" #https
    networks:
      - transcendence_network
    restart: on-failure # need to double check the 

# volumes:

networks:
  transcendence_network:
    name: transcendence_network
    driver : bridge # for making bind-mount

