# name: CI

# on:
#   push:
#     branches: [ "**" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.11'
          
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install black flake8

#       - name: Run Black
#         run: black . --check

#       - name: Run Flake8
#         run: flake8 .

#   tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dummy test
#         run: echo "Tests passed"

#   deploy:
#     needs: [lint, tests]
#     if: github.ref == 'refs/heads/master'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to Raspberry Pi
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.RASPBERRY_HOST }}
#           port: ${{ secrets.RASPBERRY_PORT }}
#           username: ${{ secrets.RASPBERRY_USER }}
#           key: ${{ secrets.RASPBERRY_SSH_KEY }}  # Ajoutez cette ligne
#           debug: true  # Pour avoir plus de détails sur l'erreur
#           script: |
#             cd workspace/ft_transcendence/
#             echo "Pulling latest changes..."
#             git pull origin master
#             echo "Stopping containers..."
#             docker-compose down
#             echo "Starting containers..."
#             docker-compose up -d
#             echo "Deployment complete!"


#######################

name: CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - prod

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run Black
        run: black . --check

      - name: Run Flake8
        run: flake8 .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy test
        run: echo "Tests passed"

  deploy:
    needs: [lint, tests]
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          port: ${{ secrets.RASPBERRY_PORT }}
          username: ${{ secrets.RASPBERRY_USER }}
          key: ${{ secrets.RASPBERRY_SSH_KEY }}  # Ajoutez cette ligne
          debug: true  # Pour avoir plus de détails sur l'erreur
          script: |
            cd workspace/ft_transcendence/ultimate_project
            echo "Pulling latest changes..."
            git pull origin prod
            echo "Stopping containers..."
            make clean
            echo "Starting containers..."
            nohup make prod &>/dev/null &
            echo "Deployment complete!"
            

            