name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run Black
        run: black . --check

      - name: Run Flake8
        run: flake8 .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy test
        run: echo "Tests passed"

  deploy:
    needs: [lint, tests]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          port: ${{ secrets.RASPBERRY_PORT }}
          username: ${{ secrets.RASPBERRY_USER }}
          key: ${{ secrets.RASPBERRY_SSH_KEY }}
          script: |
            cd workspace/ft_transcendence/
            echo "Pulling latest changes..."
            git pull origin main
            echo "Stopping containers..."
            docker-compose down
            echo "Starting containers..."
            docker-compose up -d
            echo "Deployment complete!"